repos:
  - repo: local
    hooks:
      - id: lint-shell
        name: lint-shell
        entry: bash bin/lint-shell
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit
      - id: gitleaks
        name: gitleaks
        entry: gitleaks protect --staged --verbose --redact
        language: system
        pass_filenames: false
        always_run: true
        stages:
          - pre-commit
